name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm32-unknown-unknown target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=wasm32-unknown-unknown
      - name: Prepare static files
        run: |
          mkdir _site/
          cp target/wasm32-unknown-unknown/release/mineplacer.wasm _site/game.wasm
          cp web/index.html _site/
          cp web/*.jpg _site/
          cp web/*.png _site/
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
